### ISSUE TITLE
Error when query with Mivus

### ISSUE THREAD

**Issue by zrg-team** [hwchase17/langchainjs#2431]
+ Standalone "Mivus" docker 
```
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.1.4
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus
```

Langchainjs: 0.0.135

Step 1: Index successful

```
async getDatabaseInfo(databaseId: string | number) {
    try {
      const vectorStore = await Milvus.fromExistingCollection(this.embeddingModel, {
        collectionName: `${databaseId}`,
      })
      return {
        database: `${databaseId}`,
        isInitialized: true,
        vectorStore,
      }
    } catch {
      return {
        isInitialized: false,
        database: `${databaseId}`,
        vectorStore: undefined,
      }
    }
  }
  async indexDocuments(databaseId: string | number, documents: Document[]) {
    let { isInitialized, vectorStore } = await this.getDatabaseInfo(databaseId)
    if (isInitialized) {
      await vectorStore.addDocuments(documents)
    } else {
      vectorStore = await Milvus.fromDocuments(documents, this.embeddingModel, {
        collectionName: `${databaseId}`,
      })
    }
    return vectorStore
  }
```

Step 2: Read from vector database

```
const vectorStore = Milvus.fromExistingCollection(this.embeddingModel, {
      collectionName: `${databaseId}`,
    })
vectorStore.

const relevantDocs = await codeVectorData.similaritySearch(
    question,
    12,
  )
```

## Errror

```
goroutine 71407 [select]:
milvus-standalone  | github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).BindContext.func1(0xc00012dd80, 0xc0028aa390, 0x43b7db8, 0xc00294b8c0, 0x43b7d10, 0xc002898f40)
milvus-standalone  |    /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:961 +0xf2
milvus-standalone  | created by github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).BindContext
milvus-standalone  |    /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:960 +0x9c
milvus-standalone  | 
milvus-standalone  | goroutine 71406 [chan receive]:
milvus-standalone  | github.com/milvus-io/milvus/internal/querycoord.(*taskCondition).waitToFinish(0xc002922130, 0xc002422f50, 0x0)
milvus-standalone  |    /go/src/github.com/milvus-io/milvus/internal/querycoord/condition.go:29 +0x45
milvus-standalone  | github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).waitActivateTaskDone(0xc00012dd80, 0xc001a80040, 0x43f0ba0, 0xc00291dae0, 0x43f0510, 0xc002761720)
milvus-standalone  |    /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:882 +0x155
milvus-standalone  | created by github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).scheduleLoop.func1
milvus-standalone  |    /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:631 +0x3f6
milvus-standalone  | 
milvus-standalone  | goroutine 71405 [chan receive]:
milvus-standalone  | github.com/milvus-io/milvus/internal/querycoord.(*taskCondition).waitToFinish(0xc002922128, 0xc00236b2e0, 0x0)
milvus-standalone  |    /go/src/github.com/milvus-io/milvus/internal/querycoord/condition.go:29 +0x45
milvus-standalone  | github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).waitActivateTaskDone(0xc00012dd80, 0xc001a80040, 0x43f0ba0, 0xc00291da90, 0x43f0510, 0xc002761720)
milvus-standalone  |    /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:882 +0x155
milvus-standalone  | created by github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).scheduleLoop.func1
milvus-standalone  |    /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:631 +0x3f6
milvus-standalone  | 
milvus-standalone  | goroutine 71360 [select]:
milvus-standalone  | github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).BindContext.func1(0xc00012dd80, 0xc002774c40, 0x43b7db8, 0xc00299a780, 0x43b7d10, 0xc002765640)
milvus-standalone  |    /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:961 +0xf2
milvus-standalone  | created by github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).BindContext
milvus-standalone  |    /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:960 +0x9c
milvus-standalone  | 
milvus-standalone  | goroutine 71402 [select]:
milvus-standalone  | google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc0028a4370, 0x1, 0x0, 0x0, 0x0, 0x0)
milvus-standalone  |    /go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/transport/controlbuf.go:407 +0xff
milvus-standalone  | google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc002d2f380, 0x0, 0x0)
milvus-standalone  |    /go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/transport/controlbuf.go:534 +0x1dd
milvus-standalone  | google.golang.org/grpc/internal/transport.newHTTP2Client.func3(0xc00196b0e0)
milvus-standalone  |    /go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/transport/http2_client.go:415 +0x7b
milvus-standalone  | created by google.golang.org/grpc/internal/transport.newHTTP2Client
milvus-standalone  |    /go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/transport/http2_client.go:413 +0x134e
milvus-standalone  | 
milvus-standalone  | goroutine 71400 [select]:
milvus-standalone  | google.golang.org/grpc/internal/transport.(*http2Client).keepalive(0xc00196b0e0)
milvus-standalone  |    /go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/transport/http2_client.go:1572 +0x17a
milvus-standalone  | created by google.golang.org/grpc/internal/transport.newHTTP2Client
milvus-standalone  |    /go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/transport/http2_client.go:360 +0x182b
milvus-standalone  | 
milvus-standalone  | goroutine 71455 [select]:
milvus-standalone  | github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).BindContext.func1(0xc00012dd80, 0xc0029a2130, 0x43b7db8, 0xc002a4e240, 0x43b7d10, 0xc002964f40)
milvus-standalone  |    /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:961 +0xf2
milvus-standalone  | created by github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).BindContext
milvus-standalone  |    /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:960 +0x9c
milvus-standalone  | 
milvus-standalone  | goroutine 71401 [IO wait]:
milvus-standalone  | internal/poll.runtime_pollWait(0x406b1c9400, 0x72, 0xffffffffffffffff)
milvus-standalone  |    /usr/local/go/src/runtime/netpoll.go:222 +0x55
milvus-standalone  | internal/poll.(*pollDesc).wait(0xc0034b5618, 0x72, 0x8000, 0x8000, 0xffffffffffffffff)
milvus-standalone  |    /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
milvus-standalone  | internal/poll.(*pollDesc).waitRead(...)
milvus-standalone  |    /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
milvus-standalone  | internal/poll.(*FD).Read(0xc0034b5600, 0xc0028c0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
milvus-standalone  |    /usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
milvus-standalone  | net.(*netFD).Read(0xc0034b5600, 0xc0028c0000, 0x8000, 0x8000, 0xe10cbe, 0x800000601, 0x0)
milvus-standalone  |    /usr/local/go/src/net/fd_posix.go:55 +0x4f
milvus-standalone  | net.(*conn).Read(0xc0004655d8, 0xc0028c0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
milvus-standalone  |    /usr/local/go/src/net/net.go:183 +0x91
milvus-standalone  | bufio.(*Reader).Read(0xc002d2f320, 0xc00166f000, 0x9, 0x9, 0x14, 0x40081145b8, 0x18)
milvus-standalone  |    /usr/local/go/src/bufio/bufio.go:227 +0x222
milvus-standalone  | io.ReadAtLeast(0x437a860, 0xc002d2f320, 0xc00166f000, 0x9, 0x9, 0x9, 0x18, 0x40081145b8, 0x18)
milvus-standalone  |    /usr/local/go/src/io/io.go:328 +0x87
milvus-standalone  | io.ReadFull(...)
milvus-standalone  |    /usr/local/go/src/io/io.go:347
milvus-standalone  | golang.org/x/net/http2.readFrameHeader(0xc00166f000, 0x9, 0x9, 0x437a860, 0xc002d2f320, 0x0, 0xc000000000, 0xe20175, 0xc00225b500)
milvus-standalone  |    /go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:237 +0x89
milvus-standalone  | golang.org/x/net/http2.(*Framer).ReadFrame(0xc00166efc0, 0xc00222c288, 0x5a9d5c0, 0x0, 0x0)
milvus-standalone  |    /go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:498 +0xa5
milvus-standalone  | google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc00196b0e0)
milvus-standalone  |    /go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/transport/http2_client.go:1498 +0x1a5
milvus-standalone  | created by google.golang.org/grpc/internal/transport.newHTTP2Client
milvus-standalone  |    /go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/transport/http2_client.go:365 +0xe65
milvus-standalone  | 
milvus-standalone  | goroutine 71446 [select]:
milvus-standalone  | google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc00278f240)
milvus-standalone  |    /go/pkg/mod/google.golang.org/grpc@v1.46.0/balancer_conn_wrappers.go:112 +0x9a
milvus-standalone  | created by google.golang.org/grpc.newCCBalancerWrapper
milvus-standalone  |    /go/pkg/mod/google.golang.org/grpc@v1.46.0/balancer_conn_wrappers.go:73 +0x1f8
milvus-standalone  | 
milvus-standalone  | goroutine 71450 [IO wait]:
milvus-standalone  | internal/poll.runtime_pollWait(0x406b1c9148, 0x72, 0xffffffffffffffff)
milvus-standalone  |    /usr/local/go/src/runtime/netpoll.go:222 +0x55
milvus-standalone  | internal/poll.(*pollDesc).wait(0xc002ffee98, 0x72, 0x8000, 0x8000, 0xffffffffffffffff)
milvus-standalone  |    /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
milvus-standalone  | internal/poll.(*pollDesc).waitRead(...)
milvus-standalone  |    /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
milvus-standalone  | internal/poll.(*FD).Read(0xc002ffee80, 0xc0027aa000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
milvus-standalone  |    /usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
milvus-standalone  | net.(*netFD).Read(0xc002ffee80, 0xc0027aa000, 0x8000, 0x8000, 0xe10cbe, 0x800010601, 0x0)
milvus-standalone  |    /usr/local/go/src/net/fd_posix.go:55 +0x4f
milvus-standalone  | net.(*conn).Read(0xc0025f3d50, 0xc0027aa000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
milvus-standalone  |    /usr/local/go/src/net/net.go:183 +0x91
milvus-standalone  | bufio.(*Reader).Read(0xc0027788a0, 0xc00035d700, 0x9, 0x9, 0x14, 0x0, 0x0)
milvus-standalone  |    /usr/local/go/src/bufio/bufio.go:227 +0x222
milvus-standalone  | io.ReadAtLeast(0x437a860, 0xc0027788a0, 0xc00035d700, 0x9, 0x9, 0x9, 0xb744, 0xc001f47d58, 0xe1fb2e)
milvus-standalone  |    /usr/local/go/src/io/io.go:328 +0x87
milvus-standalone  | io.ReadFull(...)
milvus-standalone  |    /usr/local/go/src/io/io.go:347
milvus-standalone  | golang.org/x/net/http2.readFrameHeader(0xc00035d700, 0x9, 0x9, 0x437a860, 0xc0027788a0, 0x0, 0x7070e0900000000, 0x439e540, 0xc00222c2a0)
milvus-standalone  |    /go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:237 +0x89
milvus-standalone  | golang.org/x/net/http2.(*Framer).ReadFrame(0xc00035d6c0, 0xc00222c2a0, 0x5a9d5c0, 0x0, 0x0)
milvus-standalone  |    /go/pkg/mod/golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/frame.go:498 +0xa5
milvus-standalone  | google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams(0xc0001afa00, 0xc002a31b00, 0x40c4668)
milvus-standalone  |    /go/pkg/mod/google.golang.org/grpc@v1.46.0/internal/transport/http2_server.go:611 +0x9b
milvus-standalone  | google.golang.org/grpc.(*Server).serveStreams(0xc0000e1500, 0x43d10f8, 0xc0001afa00)
milvus-standalone  |    /go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:906 +0x103
milvus-standalone  | google.golang.org/grpc.(*Server).handleRawConn.func1(0xc0000e1500, 0x43d10f8, 0xc0001afa00, 0xc002695856, 0xa)
milvus-standalone  |    /go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:848 +0x3f
milvus-standalone  | created by google.golang.org/grpc.(*Server).handleRawConn
milvus-standalone  |    /go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:847 +0x190
milvus-standalone  | 
milvus-standalone  | rax    0x0
milvus-standalone  | rbx    0x40bc003948
milvus-standalone  | rcx    0x27
milvus-standalone  | rdx    0x0
milvus-standalone  | rdi    0x2
milvus-standalone  | rsi    0x40bb30fc90
milvus-standalone  | rbp    0x5a918e0
milvus-standalone  | rsp    0x40bb30fc90
milvus-standalone  | r8     0x0
milvus-standalone  | r9     0x40bb30fc90
milvus-standalone  | r10    0x8
milvus-standalone  | r11    0x40022d66b0
milvus-standalone  | r12    0x40bc03c990
milvus-standalone  | r13    0x40bc019af0
milvus-standalone  | r14    0x40bb30ffc0
milvus-standalone  | r15    0x1f
milvus-standalone  | rip    0x40022d4e87
milvus-standalone  | rflags 0x246
milvus-standalone  | cs     0x33
milvus-standalone  | fs     0x0
milvus-standalone  | gs     0x0
milvus-standalone exited with code 2
```

![image](https://github.com/hwchase17/langchainjs/assets/38390571/9580b256-a253-4a47-ac0b-10ec78125b8b)

**Comment by zrg-team** [comment]
I got it to work by update docker compose
```
version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.0
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus

```
