### ISSUE TITLE
Unable to trigger action KlarnaProducts in AIPluginTool.

### ISSUE THREAD

**Issue by y12studio** [hwchase17/langchainjs#465]
In my test, approximately 10% of the time, ChatGPT is unable to trigger the KlarnaProducts action in AIPluginTool.

https://github.com/hwchase17/langchainjs/blob/5692eefef40b9f7fd6a0f2f252a721ff640507e9/examples/src/agents/aiplugin-tool.ts#L9-L26

## Expected behavior: 

OpenAI ChatGPT prompts 

````yaml
- |+
  System: Answer the following questions as best you can. You have access to the following tools:

  requests_get: A portal to the internet. Use this when you need to get specific content from a website. 
    Input should be a  url (i.e. https://www.google.com). The output will be the text response of the GET request.
  requests_post: Use this when you want to POST to a website.
    Input should be a json string with two keys: "url" and "data".
    The value of "url" should be a string, and the value of "data" should be a dictionary of 
    key-value pairs you want to POST to the url as a JSON body.
    Be careful to always use double quotes for strings in the json string
    The output will be the text response of the POST request.
  KlarnaProducts: Call this tool to get the OpenAPI spec (and usage guide) for interacting with the Klarna Shopping API. You should only call this ONCE! What is the Klarna Shopping API useful for? Search and compare prices from thousands of online shops

  The way you use the tools is by specifying a json blob, denoted below by $JSON_BLOB
  Specifically, this $JSON_BLOB should have a "action" key (with the name of the tool to use) and a "action_input" key (with the input to the tool going here). 
  The $JSON_BLOB should only contain a SINGLE action, do NOT return a list of multiple actions. Here is an example of a valid $JSON_BLOB:

  ```
  {
    "action": "calculator",
    "action_input": "1 + 2"
  }
  ```

  ALWAYS use the following format:

  Question: the input question you must answer
  Thought: you should always think about what to do
  Action: 
  ```
  $JSON_BLOB
  ```
  Observation: the result of the action
  ... (this Thought/Action/Observation can repeat N times)
  Thought: I now know the final answer
  Final Answer: the final answer to the original input question

  Begin! Reminder to always use the exact characters `Final Answer` when responding.
  Human: what t shirts are available in klarna?


````
result 
````yaml
generations:
  - - text: |
        Thought: Klarna is a payment provider, not a store. I need to check if there is a Klarna Shopping API that I can use to search for t-shirts.
        Action:
        ```
        {
          "action": "KlarnaProducts",
          "action_input": ""
        }
        ```
      message:
        text: |
          Thought: Klarna is a payment provider, not a store. I need to check if there is a Klarna Shopping API that I can use to search for t-shirts.
          Action:
          ```
          {
            "action": "KlarnaProducts",
            "action_input": ""
          }
          ```
llmOutput:
  tokenUsage:
    completionTokens: 59
    promptTokens: 469
    totalTokens: 528

````
OpenAI ChatGPT prompts 
````yaml
- |-
  System: Answer the following questions as best you can. You have access to the following tools:

  requests_get: A portal to the internet. Use this when you need to get specific content from a website. 
    Input should be a  url (i.e. https://www.google.com). The output will be the text response of the GET request.
  requests_post: Use this when you want to POST to a website.
    Input should be a json string with two keys: "url" and "data".
    The value of "url" should be a string, and the value of "data" should be a dictionary of 
    key-value pairs you want to POST to the url as a JSON body.
    Be careful to always use double quotes for strings in the json string
    The output will be the text response of the POST request.
  KlarnaProducts: Call this tool to get the OpenAPI spec (and usage guide) for interacting with the Klarna Shopping API. You should only call this ONCE! What is the Klarna Shopping API useful for? Search and compare prices from thousands of online shops

  The way you use the tools is by specifying a json blob, denoted below by $JSON_BLOB
  Specifically, this $JSON_BLOB should have a "action" key (with the name of the tool to use) and a "action_input" key (with the input to the tool going here). 
  The $JSON_BLOB should only contain a SINGLE action, do NOT return a list of multiple actions. Here is an example of a valid $JSON_BLOB:

  ```
  {
    "action": "calculator",
    "action_input": "1 + 2"
  }
  ```

  ALWAYS use the following format:

  Question: the input question you must answer
  Thought: you should always think about what to do
  Action: 
  ```
  $JSON_BLOB
  ```
  Observation: the result of the action
  ... (this Thought/Action/Observation can repeat N times)
  Thought: I now know the final answer
  Final Answer: the final answer to the original input question

  Begin! Reminder to always use the exact characters `Final Answer` when responding.
  Human: what t shirts are available in klarna?

  This was your previous work (but I haven't seen any of it! I only see what you return as final answer):
  Thought: Klarna is a payment provider, not a store. I need to check if there is a Klarna Shopping API that I can use to search for t-shirts.
  Action:
  ```
  {
    "action": "KlarnaProducts",
    "action_input": ""
  }
  ```

  Observation: Usage Guide: Use the Klarna plugin to get relevant product suggestions for any shopping or researching purpose. The query to be sent should not include stopwords like articles, prepositions and determinants. The api works best when searching for words that are related to products, like their name, brand, model or category. Links will always be returned and should be shown to the user.

  OpenAPI Spec: {"openapi":"3.0.1","info":{"version":"v0","title":"Open AI Klarna product Api"},"servers":[{"url":"https://www.klarna.com/us/shopping"}],"tags":[{"name":"open-ai-product-endpoint","description":"Open AI Product Endpoint. Query for products."}],"paths":{"/public/openai/v0/products":{"get":{"tags":["open-ai-product-endpoint"],"summary":"API for fetching Klarna product information","operationId":"productsUsingGET","parameters":[{"name":"q","in":"query","description":"query, must be between 2 and 100 characters","required":true,"schema":{"type":"string"}},{"name":"size","in":"query","description":"number of products returned","required":false,"schema":{"type":"integer"}},{"name":"budget","in":"query","description":"maximum price of the matching product in local currency, filters results","required":false,"schema":{"type":"integer"}}],"responses":{"200":{"description":"Products found","content":{"application/json":{"schema":{"$ref":"#/components/schemas/ProductResponse"}}}},"503":{"description":"one or more services are unavailable"}},"deprecated":false}}},"components":{"schemas":{"Product":{"type":"object","properties":{"attributes":{"type":"array","items":{"type":"string"}},"name":{"type":"string"},"price":{"type":"string"},"url":{"type":"string"}},"title":"Product"},"ProductResponse":{"type":"object","properties":{"products":{"type":"array","items":{"$ref":"#/components/schemas/Product"}}},"title":"ProductResponse"}}}}
  Thought:

````
result 
````yaml
generations:
  - - text: |+
        Now that I know there is a Klarna Shopping API, I can use it to search for t-shirts. I will make a GET request to the API with the query parameter "t-shirt".
        Action:
        ```
        {
          "action": "requests_get",
          "action_input": "https://www.klarna.com/us/shopping/public/openai/v0/products?q=t-shirt"
        }
        ```

      message:
        text: |+
          Now that I know there is a Klarna Shopping API, I can use it to search for t-shirts. I will make a GET request to the API with the query parameter "t-shirt".
          Action:
          ```
          {
            "action": "requests_get",
            "action_input": "https://www.klarna.com/us/shopping/public/openai/v0/products?q=t-shirt"
          }
          ```

llmOutput:
  tokenUsage:
    completionTokens: 81
    promptTokens: 963
    totalTokens: 1044

````
OpenAI ChatGPT prompts 
````yaml
- |-
  System: Answer the following questions as best you can. You have access to the following tools:

  requests_get: A portal to the internet. Use this when you need to get specific content from a website. 
    Input should be a  url (i.e. https://www.google.com). The output will be the text response of the GET request.
  requests_post: Use this when you want to POST to a website.
    Input should be a json string with two keys: "url" and "data".
    The value of "url" should be a string, and the value of "data" should be a dictionary of 
    key-value pairs you want to POST to the url as a JSON body.
    Be careful to always use double quotes for strings in the json string
    The output will be the text response of the POST request.
  KlarnaProducts: Call this tool to get the OpenAPI spec (and usage guide) for interacting with the Klarna Shopping API. You should only call this ONCE! What is the Klarna Shopping API useful for? Search and compare prices from thousands of online shops

  The way you use the tools is by specifying a json blob, denoted below by $JSON_BLOB
  Specifically, this $JSON_BLOB should have a "action" key (with the name of the tool to use) and a "action_input" key (with the input to the tool going here). 
  The $JSON_BLOB should only contain a SINGLE action, do NOT return a list of multiple actions. Here is an example of a valid $JSON_BLOB:

  ```
  {
    "action": "calculator",
    "action_input": "1 + 2"
  }
  ```

  ALWAYS use the following format:

  Question: the input question you must answer
  Thought: you should always think about what to do
  Action: 
  ```
  $JSON_BLOB
  ```
  Observation: the result of the action
  ... (this Thought/Action/Observation can repeat N times)
  Thought: I now know the final answer
  Final Answer: the final answer to the original input question

  Begin! Reminder to always use the exact characters `Final Answer` when responding.
  Human: what t shirts are available in klarna?

  This was your previous work (but I haven't seen any of it! I only see what you return as final answer):
  Thought: Klarna is a payment provider, not a store. I need to check if there is a Klarna Shopping API that I can use to search for t-shirts.
  Action:
  ```
  {
    "action": "KlarnaProducts",
    "action_input": ""
  }
  ```

  Observation: Usage Guide: Use the Klarna plugin to get relevant product suggestions for any shopping or researching purpose. The query to be sent should not include stopwords like articles, prepositions and determinants. The api works best when searching for words that are related to products, like their name, brand, model or category. Links will always be returned and should be shown to the user.

  OpenAPI Spec: {"openapi":"3.0.1","info":{"version":"v0","title":"Open AI Klarna product Api"},"servers":[{"url":"https://www.klarna.com/us/shopping"}],"tags":[{"name":"open-ai-product-endpoint","description":"Open AI Product Endpoint. Query for products."}],"paths":{"/public/openai/v0/products":{"get":{"tags":["open-ai-product-endpoint"],"summary":"API for fetching Klarna product information","operationId":"productsUsingGET","parameters":[{"name":"q","in":"query","description":"query, must be between 2 and 100 characters","required":true,"schema":{"type":"string"}},{"name":"size","in":"query","description":"number of products returned","required":false,"schema":{"type":"integer"}},{"name":"budget","in":"query","description":"maximum price of the matching product in local currency, filters results","required":false,"schema":{"type":"integer"}}],"responses":{"200":{"description":"Products found","content":{"application/json":{"schema":{"$ref":"#/components/schemas/ProductResponse"}}}},"503":{"description":"one or more services are unavailable"}},"deprecated":false}}},"components":{"schemas":{"Product":{"type":"object","properties":{"attributes":{"type":"array","items":{"type":"string"}},"name":{"type":"string"},"price":{"type":"string"},"url":{"type":"string"}},"title":"Product"},"ProductResponse":{"type":"object","properties":{"products":{"type":"array","items":{"$ref":"#/components/schemas/Product"}}},"title":"ProductResponse"}}}}
  Thought:Now that I know there is a Klarna Shopping API, I can use it to search for t-shirts. I will make a GET request to the API with the query parameter "t-shirt".
  Action:
  ```
  {
    "action": "requests_get",
    "action_input": "https://www.klarna.com/us/shopping/public/openai/v0/products?q=t-shirt"
  }
  ```


  Observation: {"products":[{"name":"Psycho Bunny Mens Copa Gradient Logo Graphic Tee","url":"https://www.klarna.com/us/shopping/pl/cl10001/3203663222/Clothing/Psycho-Bunny-Mens-Copa-Gradient-Logo-Graphic-Tee/?source=openai","price":"$35.00","attributes":["Material:Cotton","Target Group:Man","Color:White,Blue,Black,Orange","Neckline:Round"]},{"name":"T-shirt","url":"https://www.klarna.com/us/shopping/pl/cl10001/3203506327/Clothing/T-shirt/?source=openai","price":"$20.45","attributes":["Material:Cotton","Target Group:Man","Color:Gray,White,Blue,Black,Orange","Neckline:Round"]},{"name":"Palm Angels Bear T-shirt - Black","url":"https://www.klarna.com/us/shopping/pl/cl10001/3201090513/Clothing/Palm-Angels-Bear-T-shirt-Black/?source=openai","price":"$167.95","attributes":["Material:Cotton","Target Group:Man","Color:Black"]},{"name":"Tommy Hilfiger Essential Flag Logo T-shirt","url":"https://www.klarna.com/us/shopping/pl/cl10001/3201840629/Clothing/Tommy-Hilfiger-Essential-Flag-Logo-T-shirt/?source=openai","price":"$22.52","attributes":["Material:Cotton","Target Group:Man","Color:Red,Gray,White,Blue,Black","Pattern:Solid Color","Environmental Attributes :Organic","Neckline:Round"]},{"name":"Coach Outlet Signature T Shirt","url":"https://www.klarna.com/us/shopping/pl/cl10001/3203005573/Clothing/Coach-Outlet-Signature-T-Shirt/?source=openai","price":"$75.00","attributes":["Material:Cotton","Target Group:Man","Color:Gray","Neckline:Round"]}]}
  Thought:

````
result 
````yaml
generations:
  - - text: |-
        The available t-shirts are: 
        - Psycho Bunny Mens Copa Gradient Logo Graphic Tee
        - T-shirt
        - Palm Angels Bear T-shirt - Black
        - Tommy Hilfiger Essential Flag Logo T-shirt
        - Coach Outlet Signature T Shirt

        Final Answer: Psycho Bunny Mens Copa Gradient Logo Graphic Tee, T-shirt, Palm Angels Bear T-shirt - Black, Tommy Hilfiger Essential Flag Logo T-shirt, Coach Outlet Signature T Shirt.
      message:
        text: |-
          The available t-shirts are: 
          - Psycho Bunny Mens Copa Gradient Logo Graphic Tee
          - T-shirt
          - Palm Angels Bear T-shirt - Black
          - Tommy Hilfiger Essential Flag Logo T-shirt
          - Coach Outlet Signature T Shirt

          Final Answer: Psycho Bunny Mens Copa Gradient Logo Graphic Tee, T-shirt, Palm Angels Bear T-shirt - Black, Tommy Hilfiger Essential Flag Logo T-shirt, Coach Outlet Signature T Shirt.
llmOutput:
  tokenUsage:
    completionTokens: 87
    promptTokens: 1473
    totalTokens: 1560

````

## Actual behavior:

OpenAI ChatGPT prompts 

````yaml
- |+
  System: Answer the following questions as best you can. You have access to the following tools:

  requests_get: A portal to the internet. Use this when you need to get specific content from a website. 
    Input should be a  url (i.e. https://www.google.com). The output will be the text response of the GET request.
  requests_post: Use this when you want to POST to a website.
    Input should be a json string with two keys: "url" and "data".
    The value of "url" should be a string, and the value of "data" should be a dictionary of 
    key-value pairs you want to POST to the url as a JSON body.
    Be careful to always use double quotes for strings in the json string
    The output will be the text response of the POST request.
  KlarnaProducts: Call this tool to get the OpenAPI spec (and usage guide) for interacting with the Klarna Shopping API. You should only call this ONCE! What is the Klarna Shopping API useful for? Search and compare prices from thousands of online shops

  The way you use the tools is by specifying a json blob, denoted below by $JSON_BLOB
  Specifically, this $JSON_BLOB should have a "action" key (with the name of the tool to use) and a "action_input" key (with the input to the tool going here). 
  The $JSON_BLOB should only contain a SINGLE action, do NOT return a list of multiple actions. Here is an example of a valid $JSON_BLOB:

  ```
  {
    "action": "calculator",
    "action_input": "1 + 2"
  }
  ```

  ALWAYS use the following format:

  Question: the input question you must answer
  Thought: you should always think about what to do
  Action: 
  ```
  $JSON_BLOB
  ```
  Observation: the result of the action
  ... (this Thought/Action/Observation can repeat N times)
  Thought: I now know the final answer
  Final Answer: the final answer to the original input question

  Begin! Reminder to always use the exact characters `Final Answer` when responding.
  Human: what t shirts are available in klarna?


````
result 
````yaml
generations:
  - - text: |
        Thought: Klarna is a payment provider, not a shopping platform. I need to check if they have an API that can be used to search for products.
        Action:
        ```
        {
          "action": "requests_get",
          "action_input": "https://developers.klarna.com/api/#shopping-api"
        }
        ```
      message:
        text: |
          Thought: Klarna is a payment provider, not a shopping platform. I need to check if they have an API that can be used to search for products.
          Action:
          ```
          {
            "action": "requests_get",
            "action_input": "https://developers.klarna.com/api/#shopping-api"
          }
          ```
llmOutput:
  tokenUsage:
    completionTokens: 66
    promptTokens: 469
    totalTokens: 535

````
OpenAI ChatGPT prompts (with Observation: html content )

````yaml
- "System: Answer the following questions as best you can. You have access to the following tools:\n\nrequests_get: A portal to the internet. Use this when you need to get specific content from a website. \n  Input should be a  url (i.e. https://www.google.com). The output will be the text response of the GET request.\nrequests_post: Use this when you want to POST to a website.\n  Input should be a json string with two keys: \"url\" and \"data\".\n  The value of \"url\" should be a string, and the value of \"data\" should be a dictionary of \n  key-value pairs you want to POST to the url as a JSON body.\n  Be careful to always use double quotes for strings in the json string\n  The output will be the text response of the POST request.\nKlarnaProducts: Call this tool to get the OpenAPI spec (and usage guide) for interacting with the Klarna Shopping API. You should only call this ONCE! What is the Klarna Shopping API useful for? Search and compare prices from thousands of online shops\n\nThe way you use the tools is by specifying a json blob, denoted below by $JSON_BLOB\nSpecifically, this $JSON_BLOB should have a \"action\" key (with the name of the tool to use) and a \"action_input\" key (with the input to the tool going here). \nThe $JSON_BLOB should only contain a SINGLE action, do NOT return a list of multiple actions. Here is an example of a valid $JSON_BLOB:\n\n```\n{\n  \"action\": \"calculator\",\n  \"action_input\": \"1 + 2\"\n}\n```\n\nALWAYS use the following format:\n\nQuestion: the input question you must answer\nThought: you should always think about what to do\nAction: \n```\n$JSON_BLOB\n```\nObservation: the result of the action\n... (this Thought/Action/Observation can repeat N times)\nThought: I now know the final answer\nFinal Answer: the final answer to the original input question\n\nBegin! Reminder to always use the exact characters `Final Answer` when responding.\nHuman: what t shirts are available in klarna?\n\nThis was your previous work (but I haven't seen any of it! I only see what you return as final answer):\nThought: Klarna is a payment provider, not a shopping platform. I need to check if they have an API that can be used to search for products.\nAction:\n```\n{\n  \"action\": \"requests_get\",\n  \"action_input\": \"https://developers.klarna.com/api/#shopping-api\"\n}\n```\n\nObservation: <!DOCTYPE html><html lang=\"en-US\"><head><meta charSet=\"utf-8\"/><meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\"/><meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover\"/><script>window._onRedoclyRoute....````
