### ISSUE TITLE
Weaviate Vectore Store: Error "no graphql provider present, this is most likely because no schema is present. Import a schema first!"

### ISSUE THREAD

**Issue by heresandyboy** [hwchase17/langchainjs#926]
I am trying to get started with Weaviate via LangChainJS, for the first time, and I am migrating my code from using Pinecone.

In my code below I am creating some documents from a PDF and using embeddings from open AI to import the documents to Weaviate. I am just running Weaviate in docker locally with a basic default docker-compose from their generator in their docs site.

I get no errors at all from `WeaviateStore.fromDocuments` but I can not retrieve any data as it seems no schema has been generated after importing the data.

I get the error from `store.similaritySearch`:
`no graphql provider present, this is most likely because no schema is present. Import a schema first`
```bash
'Error in similaritySearch' Error: GraphQL Error (Code: 422): 
{"response":
{"error":[{"message":"no graphql provider present, this is most likely because no schema is present. 
Import a schema first!"}],"status":422,"headers":{}},
"request":{"query":"{Get{pdf-test(nearVector:{vector:
[-0.025541332,-0.013953761,0.01518418,-0.012939679,-0.014792069,0.007930117,-0.023
...
```

It is my assumption that schemas are auto generated based on the data I put into Weaviate, sic :  https://weaviate.io/developers/weaviate/configuration/schema-configuration#auto-schema

Here is my code, if anyone can help me figure out what I am doing wrong:

```typescript
import { RecursiveCharacterTextSplitter } from 'langchain/text_splitter';
import { OpenAIEmbeddings } from 'langchain/embeddings/openai';
import { WeaviateStore } from 'langchain/vectorstores/weaviate';
import { client } from '@/utils/weaviate-client';
import { CustomPDFLoader } from '@/utils/customPDFLoader';
import { WEAVIATE_INDEX_NAME } from '@/config/weaviate';
import { DirectoryLoader } from 'langchain/document_loaders/fs/directory';

/* Name of directory to retrieve your files from */
const filePath = 'public/docs';

export const run = async () => {
  try {
    /*load raw docs from the all files in the directory */
    const directoryLoader = new DirectoryLoader(filePath, {
      '.pdf': (path) => new CustomPDFLoader(path),
    });

    // const loader = new PDFLoader(filePath);
    const rawDocs = await directoryLoader.load();

    /* Split text into chunks */
    const textSplitter = new RecursiveCharacterTextSplitter({
      chunkSize: 1000,
      chunkOverlap: 200,
    });

    const docs = await textSplitter.splitDocuments(rawDocs);
    console.log('split docs', docs);

    console.log('creating vector store...');
    /*create and store the embeddings in the vectorStore*/
    const embeddings = new OpenAIEmbeddings();

    //embed the PDF documents
    const store = await WeaviateStore.fromDocuments(docs, embeddings, {
      client,
      indexName: WEAVIATE_INDEX_NAME,
      textKey: 'text',
      metadataKeys: ['source', 'pdf_numpages', 'loc'],
    });

    const results = await store.similaritySearch('broadband', 1);
    console.log(results);
  } catch (error) {
    console.log('error', error);
    throw new Error('Failed to ingest your data');
  }
};

(async () => {
  await run();
  console.log('ingestion complete');
})();

```

Here is my docker compose if it helps:

```yaml
---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.18.3
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      OPENAI_APIKEY: **REDACTED**
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai'
      CLUSTER_HOSTNAME: 'node1'
      AUTOSCHEMA_ENABLED: 'true'
    volumes:
      - ./weaviate:/var/lib/weaviate
...

```

Here are the relevant env vars:

```bash
WEAVIATE_INDEX_NAME=pdf-test
WEAVIATE_SCHEME=http
WEAVIATE_HOST=127.0.0.1:8080

```
